INCLUDES = -Iinclude -I../UsageEnvironment/include
PREFIX = /usr/local
LIBDIR = $(PREFIX)/lib
##### Change the following for your environment:
PREFIX = /home/mamengchao/vlc/vlc-3.0/contrib/i686-w64-mingw32
LIBDIR = /home/mamengchao/vlc/vlc-3.0/contrib/i686-w64-mingw32/lib
